version: '3.8'

services:
  backend:
    build: .
    environment:
      ENVIRONMENT: 'dev'
      POSTGRES_HOST: 'postgres'
      POSTGRES_PORT: '5432'
      POSTGRES_USERNAME: 'root'
      POSTGRES_PASSWORD: 'root'
      POSTGRES_DATABASE: 'don_receipt'
      BCRYPT_SALT_ROUNDS: '10'
    depends_on:
      postgres:
        condition: service_healthy
    restart: 'no'
    ports:
      - '3001:3000'

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PORT: '5432'
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root'
      POSTGRES_DB: 'don_receipt'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U root -d don_receipt']
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - '5433:5432'

volumes:
  postgres_data:
